### ISSUE TITLE
Scale up MinIO Minimal

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/minio-deploy#6]
I have a user who wants to upload 2TB of data this week; I just want to make sure we don't break anything.

What's our scaling setup right now? Do we autoscale storage? How do I compute the current max?

**Comment by blairdrummond** [comment]
CC @zachomedia @justbert

**Comment by sylus** [comment]
There is no max that I know off but we can scale out the PVC, I just need @brendangadd to approve this before I can action.

**Comment by brendangadd** [comment]
@sylus Approved! :)

We scale storage by scaling instances, correct?

**Comment by sylus** [comment]
This is done since the new tenants are much bigger now.
